/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: dcb0be1d18f5a061447cbc2b09084969)
interface __BaseEnv_Env {
  EMAIL: SendEmail;
  ASSETS: Fetcher;
  EMAIL_FROM: string;
  SLACK_BOT_TOKEN: string;
  SLACK_BOT_USER_ID: string;
  SLACK_SIGNING_SECRET: string;
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_WEBHOOK_SECRET: string;
  Directory: DurableObjectNamespace<import("./src/server").Directory>;
  Conversation: DurableObjectNamespace<import("./src/server").Conversation>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Conversation" | "Directory";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "EMAIL_FROM"
      | "SLACK_BOT_TOKEN"
      | "SLACK_BOT_USER_ID"
      | "SLACK_SIGNING_SECRET"
      | "TELEGRAM_BOT_TOKEN"
      | "TELEGRAM_WEBHOOK_SECRET"
    >
  > {}
}
